### PR TITLE
Fix compilation error caused by retroactive attribute usage in environments < Swift 6

### PR DESCRIPTION
**Pull request by sanghyeok-kim**
### Short description 📝

When building Tuist in environments that do not use Swift 6 (e.g., Swift 5.10, currently used in Manifest), the following compilation failure occurs by attribute [retroactive](https://github.com/swiftlang/swift-evolution/blob/main/proposals/0364-retroactive-conformance-warning.md):

CleanShot 2025-01-18 at 11 56 41@2x

To address this issue, version exception handling was added to ensure the code does not fail to compile in environments below Swift 6.

### How to test the changes locally 🧐

> Include a set of steps for the reviewer to test the changes locally (see [the documentation](https://docs.tuist.io/contributors/get-started) for reference).

### Contributor checklist ✅

- [x] The code has been linted using run `mise run lint-fix`
- [x] The change is tested via unit testing or acceptance testing, or both
- [x] The title of the PR is formulated in a way that is usable as a changelog entry
- [x] In case the PR introduces changes that affect users, the documentation has been updated

### Reviewer checklist ✅

- [ ] The code architecture and patterns are consistent with the rest of the codebase
- [ ] Reviewer has checked that, if needed, the PR includes the label `changelog:added`, `changelog:fixed`, or `changelog:changed`, and the title is usable as a changelog entry

### CODE REVIEW

**Review by pepicrft — APPROVED** [review]

File: app/TuistApp/Sources/Extensions/SimulatorDeviceAndRuntime+Extras.swift [hunk 1]
```diff
@@ -1,9 +1,18 @@
 import Foundation
 import TuistCore
 
-extension SimulatorDeviceAndRuntime: @retroactive Comparable {
-    public static func < (lhs: SimulatorDeviceAndRuntime, rhs: SimulatorDeviceAndRuntime) -> Bool {
-        if lhs.device.name == rhs.device.name { return lhs.runtime.name < rhs.runtime.name }
-        else { return lhs.device.name < rhs.device.name }
+#if swift(>=6)
+    extension SimulatorDeviceAndRuntime: @retroactive Comparable {
```
Comment (pepicrft) [inline app/TuistApp/Sources/Extensions/SimulatorDeviceAndRuntime+Extras.swift:5]: Is this the only model that causes issues @sanghyeok-kim ?

**Comment by pepicrft** [comment]
@all-contributors add @sanghyeok-kim for code

File: app/TuistApp/Sources/Extensions/SimulatorDeviceAndRuntime+Extras.swift (hunk 1 above)
Comment (sanghyeok-kim) [reply app/TuistApp/Sources/Extensions/SimulatorDeviceAndRuntime+Extras.swift:5]: Yes, other cases work fine with Swift 5 without any issues.

Comment (sanghyeok-kim) [reply app/TuistApp/Sources/Extensions/SimulatorDeviceAndRuntime+Extras.swift:5]: @pepicrft 

Oh, just found some additional issues in the test code.

Features introduced in [Swift Testing](https://www.swift.org/blog/announcing-swift-6/) are causing compilation errors in the Swift 5 environment:

- import Testing
- @Test
- @Suite
- #expect

**Review by fortmarek — COMMENTED** [review]
Hey @sanghyeok-kim 👋 

I don't fully understand why this is needed – have you run into this when trying to build the `TuistApp` in an Xcode version that doesn't have support for Swift 6? Or what was the exact scenario?

In your PR description, you mentioned:

> When building Tuist in environments that do not use Swift 6 (e.g., Swift 5.10, currently used in Manifest),

What is your environment? I would rather not cater for environments that don't support Swift 6 when it comes to code inside the Tuist app that's not used as a package.

**Comment by sanghyeok-kim** [comment]
@fortmarek

My environment is:
- Xcode 15.4
- Swift 5.10
---

Currently, none of the `Project.swift` files, including TuistApp, specify a Swift version.

And since Manifest uses Swift 5.10 as specified in the `Tuist.swift` file, though I understand this refers to the Swift version for Manifest and not the workspace being built, I assumed that `Tuist` and `TuistApp` module would also build in a Swift 5.10 environment.

Given that Swift 6 syntax is used, especially frequently in test code, would it be correct to understand that Swift 6 is required for contributors to build and run Tuist?

**Comment by fortmarek** [comment]
> Given that Swift 6 syntax is used, especially frequently in test code, would it be correct to understand that Swift 6 is required for contributors to build and run Tuist?

Yes, that is correct. This is mentioned in the minimum requirements: https://docs.tuist.dev/en/contributors/get-started#minimum-requirements (Xcode 16.0 is the first Xcode version that shipped with Swift 6).

I'd suggest that you upgrade your Xcode version – at least when contributing to Tuist. Is there any strong reason why you need to compile the Tuist app using Xcode 15.x?

I'm gonna close this, but thanks for taking a look 😌
