### ISSUE TITLE
SPM integration is missing in documentation

### ISSUE THREAD

**Issue by rowwingman** [tuist/tuist#5600]
### What happened?

After migration to support Package.swift. There is not clear how to fetch dependencies or how to declare them. Should I create a Package.swift file inside Tuist folder, or should I provide packages inside `Project` now. 

I tried to fetch dependencies by command `swift package resolve`. I get expected result that error: no such module 'ProjectDescription' import ProjectDescription.

There should be a migration note from Dependencies.swift to Package.swift. This [MR](https://github.com/tuist/tuist/pull/5503) marked as non breaking changes. But in fact it is, as it is breaking Dependencies.swift file. After this change tuist generate fails.

What is the way to add SPM dependencies?
How to fetch them?
How to add this dependencies to the project?

### How do we reproduce it?

none

### Error log

none

### macOS version

14.1.1

### Tuist version

3.33.3

### Xcode version

15.0.1

**Comment by rowwingman** [comment]
What I found that you need to declare SPM depdenecies in Package.swift file. and inside Dependencies.swift you need to provide `swiftPackageManager: SwiftPackageManagerDependencies()`. However when you run `tuist fetch --update` I still have the same error `no such module 'ProjectDescription' import ProjectDescription.`

**Comment by fortmarek** [comment]
> After migration to support Package.swift. There is not clear how to fetch dependencies or how to declare them. Should I create a Package.swift file inside Tuist folder, or should I provide packages inside Project now.

You should use `Tuist/Package.swift` but we currently still support defining your dependencies in `Tuist/Dependencies.swift` (which is why the attached PR was not breaking). You should still use `tuist fetch` regardless of which integration you use. Would be happy to look into this further but would be easier with a reproduction case 🙂

**Comment by rowwingman** [comment]
this is my Tuist/Package.swift
`
// swift-tools-version: 5.9
import ProjectDescription

let package = Package(
    name: "PackageName",
    dependencies: [
        .remote(url: "https://github.com/pointfreeco/swift-snapshot-testing", requirement: .upToNextMajor(from: "1.0.0")),
        .remote(url: "https://github.com/onevcat/Kingfisher.git", requirement: .upToNextMajor(from: "7.0.0")),
        .package(url: "https://github.com/psharanda/Atributika.git", .upToNextMajor(from: "5.0.0")),
        .remote(url: "https://github.com/AppsFlyerSDK/AppsFlyerFramework", requirement: .upToNextMajor(from: "6.0.0")),
        .package(url: "https://github.com/GoogleCloudPlatform/recaptcha-enterprise-mobile-sdk", .upToNextMajor(from: "18.0.0")),
    ]
)
`

this is my log:
`
tuist fetch --update
Resolving and fetching plugins.
Plugins resolved and fetched successfully.
Updating dependencies.
Installing Swift Package Manager dependencies.
error: 'swiftpackagemanager': Invalid manifest (compiled with: ["/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swiftc", "-vfsoverlay", "/var/folders/_c/xz16spxn1f396m4h6lms8jwh0000gn/T/TemporaryDirectory.fsztAS/vfs.yaml", "-L", "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/pm/ManifestAPI", "-lPackageDescription", "-Xlinker", "-rpath", "-Xlinker", "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/pm/ManifestAPI", "-target", "arm64-apple-macosx13.0", "-sdk", "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.0.sdk", "-F", "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/Library/Frameworks", "-I", "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/usr/lib", "-L", "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/usr/lib", "-swift-version", "5", "-I", "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/pm/ManifestAPI", "-sdk", "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.0.sdk", "-package-description-version", "5.9.0", "/Users/user_name/git_tree/project_folder/Tuist/Dependencies/SwiftPackageManager/Package.swift", "-Xfrontend", "-disable-implicit-concurrency-module-import", "-Xfrontend", "-disable-implicit-string-processing-module-import", "-o", "/var/folders/_c/xz16spxn1f396m4h6lms8jwh0000gn/T/TemporaryDirectory.TXnEqU/swiftpackagemanager-manifest"])
error: fatalError
/Users/user_name/git_tree/project_folder/Tuist/Dependencies/SwiftPackageManager/Package.swift:2:8: error: no such module 'ProjectDescription'
import ProjectDescription
       ^
The 'swift' command exited with error code 1
Consider creating an issue using the following link: https://github.com/tuist/tuist/issues/new/choose
`

so the problem with the import ProjectDescription. 


This is what I have if I don't change my Dependencies.swift file:
`
Resolving and fetching plugins.
Plugins resolved and fetched successfully.
Resolving and fetching dependencies.
The 'swift' command exited with error code 1 and message:
/Users/user_name/git_tree/project_folder/Tuist/Dependencies.swift:5:26: error: cannot convert value of type '[Any]' to expected argument type 'SwiftPackageManagerDependencies?'
    swiftPackageManager: [
                         ^
/Users/user_name/git_tree/project_folder/Tuist/Dependencies.swift:6:10: error: type 'Any' has no member 'remote'
        .remote(url: "https://github.com/pointfreeco/swift-snapshot-testing", requirement: .upToNextMajor(from: "1.0.0")),
        ~^~~~~~
/Users/user_name/git_tree/project_folder/Tuist/Dependencies.swift:6:93: error: cannot infer contextual base in reference to member 'upToNextMajor'
        .remote(url: "https://github.com/pointfreeco/swift-snapshot-testing", requirement: .upToNextMajor(from: "1.0.0")),
                                                                                           ~^~~~~~~~~~~~~
/Users/user_name/git_tree/project_folder/Tuist/Dependencies.swift:7:10: error: type 'Any' has no member 'remote'
        .remote(url: "https://github.com/onevcat/Kingfisher.git", requirement: .upToNextMajor(from: "7.0.0")),
        ~^~~~~~
/Users/user_name/git_tree/project_folder/Tuist/Dependencies.swift:7:81: error: cannot infer contextual base in reference to member 'upToNextMajor'
        .remote(url: "https://github.com/onevcat/Kingfisher.git", requirement: .upToNextMajor(from: "7.0.0")),
                                                                               ~^~~~~~~~~~~~~
/Users/user_name/git_tree/project_folder/Tuist/Dependencies.swift:8:10: error: type 'Any' has no member 'package'
        .package(url: "https://github.com/psharanda/Atributika.git", .upToNextMajor(from: "5.0.0")),
        ~^~~~~~~
/Users/user_name/git_tree/project_folder/Tuist/Dependencies.swift:8:71: error: cannot infer contextual base in reference to member 'upToNextMajor'
        .package(url: "https://github.com/psharanda/Atributika.git", .upToNextMajor(from: "5.0.0")),
                                                                     ~^~~~~~~~~~~~~
/Users/user_name/git_tree/project_folder/Tuist/Dependencies.swift:9:10: error: type 'Any' has no member 'remote'
        .remote(url: "https://github.com/AppsFlyerSDK/AppsFlyerFramework", requirement: .upToNextMajor(from: "6.0.0")),
        ~^~~~~~
/Users/user_name/git_tree/project_folder/Tuist/Dependencies.swift:9:90: error: cannot infer contextual base in reference to member 'upToNextMajor'
        .remote(url: "https://github.com/AppsFlyerSDK/AppsFlyerFramework", requirement: .upToNextMajor(from: "6.0.0")),
                                                                                        ~^~~~~~~~~~~~~
/Users/user_name/git_tree/project_folder/Tuist/Dependencies.swift:10:10: error: type 'Any' has no member 'package'
        .package(url: "https://github.com/GoogleCloudPlatform/recaptcha-enterprise-mobile-sdk", .upToNextMajor(from: "18.0.0")),
        ~^~~~~~~
/Users/user_name/git_tree/project_folder/Tuist/Dependencies.swift:10:98: error: cannot infer contextual base in reference to member 'upToNextMajor'
        .package(url: "https://github.com/GoogleCloudPlatform/recaptcha-enterprise-mobile-sdk", .upToNextMajor(from: "18.0.0")),
                                                                                                ~^~~~~~~~~~~~~

Consider creating an issue using the following link: https://github.com/tuist/tuist/issues/new/choose
Resolved cache profile 'Development' from Tuist's defaults
Couldn't decode the DependenciesGraph from the serialized JSON file. Running `tuist fetch` should solve the problem.
Consider creating an issue using the following link: https://github.com/tuist/tuist/issues/new/choose
`

So after updating to 3.33.3. version it breaks the existing Dependencies.swift file.

If I downgrade to the previous version that I used 3.29.0, everything works as expected

**Comment by bdbergeron** [comment]
@rowwingman Your `Package.swift` file should import the `PackageDescription` module, which is the SPM package definition import. The `ProjectDescription` module you're trying to import is for Tuist project configuration.

**Comment by rowwingman** [comment]
@bdbergeron thank you. It works. However now I have a problem with connecting this dependencies to the project. previously I add it with .external(name: "name of the dependency"), how should I do it with Package.swift?

**Comment by rowwingman** [comment]
I think I found, this one is the correct one https://tuist.github.io/tuist/main/documentation/projectdescription/targetdependency/package(product:type:)

**Comment by bdbergeron** [comment]
You should still use `.external()` for SPM dependencies brought in through Tuist's dependencies system. Take a look at the [app_with_spm_dependencies](https://github.com/tuist/tuist/tree/main/fixtures/app_with_spm_dependencies) fixture to see a good example of this.
