### PR TITLE
Fix: Excluding files from target doesn't work in all cases

### PR DESCRIPTION
**Pull request by vytis**
### Short description 📝

A way to exclude source files from the target was introduced with #808 but it was failing to exclude paths in subdirectories. 

Let's say we have a pattern:
```
.init("sources/**/*.swift", excluding: "sources/**/*Tests.swift")`
```

Then:
* It works as expected and matches `sources/a.swift` and ignores `sources/aTests.swift`
* it wrongly includes both `sources/foo/b.swift` and `sources/foo/bTests.swift`

### Solution 📦

The bug is caused because both include and exclude globs were using the same base directory. 
The fix was to use the base directory of exclude glob.

### CODE REVIEW

**Comment by paciej00** [comment]
Guys, is there a way of using a `tuist` built from this branch? When compiling it locally I get some errors:

```
swift build -c release
.../tuist/Sources/TuistSupportTesting/Extensions/ArgumentParser+TestData.swift:2:18: error: module 'SPMUtility' was not compiled for testing
```

@vytis thank you for fixing the issue with excluding globs 🙌🏻 I started investigating the problem today and yet you have just solved it 👍

**Comment by pepibumur** [comment]
> Guys, is there a way of using a tuist built from this branch? When compiling it locally I get some errors:

Yes. You can do `tuist local a07a6c7c820745a3bfac5dc959f89c690a30df23` and you should be able to test it. You can read more about the local command [here](https://tuist.io/docs/usage/managing-versions/#tuist-local)
