### PR TITLE
Fix integrating static xcframeworks linked through dynamic xcframeworks

### PR DESCRIPTION
**Pull request by fortmarek**
Resolves https://github.com/tuist/tuist/issues/6609

### Short description 📝

This PR fixes issue https://github.com/tuist/tuist/issues/6609, more specifically [this](https://github.com/tuist/tuist/issues/6609#issuecomment-2336861272) comment.

The comment refers to the following graph:
```
App -> Dynamic framework -> GoogleMaps (Static xcframework)
```

Running `GoogleMaps` only works when `Dynamic framework` is pulled in as sources. But when using `tuist cache`, replacing `Dynamic framework` leads to duplicated GoogleMaps symbols – in which case, the GoogleMaps library breaks.

Why do we have duplicated symbols in the first place?

That business logic was introduced in https://github.com/tuist/tuist/pull/6613 to try and solve build issues that boil down to linking a static xcframework through a dynamic xcframework (see more [here](https://forums.swift.org/t/issue-with-third-party-dependencies-inside-a-xcframework-through-swiftpm/41977/3)).

Instead of duplicate linking the static xcframework, we can point the downstream targets (in our case, `App`) to the relevant symbols using extra linking flags that point to the headers and the relevant modulemap (the relevant settings are `OTHER_SWIFT_FLAGS`, `OTHER_C_FLAGS`, and `HEADER_SEARCH_PATHS`). The xcframework contains headers and modulemaps for all architectures, but both _should_ be the same across all of the available archs – so we only point to one.

This strategy only works for Objective C dependencies – something similar should be feasible also for Swift modules, but we'd need to point to the `.swiftmodule` instead of `.modulemap` which is meant for Objective C consumers. Since there have been no complaints around Swift modules that would be affected by this scenario, we decided to keep the duplicate linking for Swift modules – for now, at least.

### How to test the changes locally 🧐

In `app_with_google_maps`, run:
- `tuist cache`
- `tuist generate App`
- Run the app -> there should be no duplicate symbol warnings and the map should render correctly.

### Contributor checklist ✅

- [x] The code has been linted using run `mise run lint-fix`
- [x] The change is tested via unit testing or acceptance testing, or both
- [x] The title of the PR is formulated in a way that is usable as a changelog entry
- [x] In case the PR introduces changes that affect users, the documentation has been updated

### Reviewer checklist ✅

- [x] The code architecture and patterns are consistent with the rest of the codebase
- [x] Reviewer has checked that, if needed, the PR includes the label `changelog:added`, `changelog:fixed`, or `changelog:changed`, and the title is usable as a changelog entry

### CODE REVIEW

File: Sources/TuistCore/Graph/GraphTraverser.swift [hunk 1]
```diff
@@ -461,23 +461,17 @@ public class GraphTraverser: GraphTraversing {
...
+            name: name
+        )
 
         let staticXCFrameworksLinkedByDynamicXCFrameworkDependencies = filterDependencies(
-            from: Set(precompiledDynamicLibrariesAndFrameworks).filter {
-                $0.xcframeworkDependency != nil
+            from: Set(precompiledDynamicLibrariesAndFrameworks).filter { $0.xcframeworkDependency != nil },
+            test: {
+                $0.xcframeworkDependency?.linking == .static &&
+                    $0.xcframeworkDependency?.path.glob("**/*.swiftmodule").isEmpty == false
```
Comment (pepicrft) [inline Sources/TuistCore/Graph/GraphTraverser.swift:473]: I'd be consistent with other metadata associated with an `.xcframework` and load this information in memory when the XCFramework dependency is loaded (e.g. `containsSwiftModules`, `containsModuleMaps`)

File: Sources/TuistKit/Mappers/Graph/StaticXCFrameworkModuleMapGraphMapper.swift [hunk 2]
```diff
@@ -0,0 +1,182 @@
+import Foundation
+import Path
+import TuistCore
+import TuistSupport
+import XcodeGraph
+
+public final class StaticXCFrameworkModuleMapGraphMapper: GraphMapping {
+    private let fileHandler: FileHandling
```
Comment (pepicrft) [inline Sources/TuistKit/Mappers/Graph/StaticXCFrameworkModuleMapGraphMapper.swift:8]: Can't we use `FileSystem` here?

File: Sources/TuistKit/Mappers/Graph/StaticXCFrameworkModuleMapGraphMapper.swift [hunk 3]
```diff
@@ -0,0 +1,182 @@
+import Foundation
+import Path
+import TuistCore
+import TuistSupport
+import XcodeGraph
+
+public final class StaticXCFrameworkModuleMapGraphMapper: GraphMapping {
```
Comment (pepicrft) [inline Sources/TuistKit/Mappers/Graph/StaticXCFrameworkModuleMapGraphMapper.swift:7]: I'd add a documentation here explaining what this mapper solves. It might not be obvious from the name.

File: Sources/TuistKit/Mappers/Graph/StaticXCFrameworkModuleMapGraphMapper.swift [hunk 4]
```diff
@@ -0,0 +1,182 @@
...
+        return "-fmodule-map-file=\"$(SRCROOT)/\(derivedDirectory.appending(components: name, "Headers", "module.modulemap").relative(to: project.path).pathString)\""
+    }
+
+    private func derivedDirectory(graph: Graph) -> AbsolutePath {
+        let packageDirectoryPath: AbsolutePath
+        if fileHandler.exists(graph.path.appending(component: Constants.SwiftPackageManager.packageSwiftName)) {
+            packageDirectoryPath = graph.path
+        } else {
+            packageDirectoryPath = graph.path.appending(component: Constants.tuistDirectoryName)
+        }
```
Comment (pepicrft) [inline Sources/TuistKit/Mappers/Graph/StaticXCFrameworkModuleMapGraphMapper.swift:106]: Is this the only place in the codebase where we need to get the `.build` directory based on the location of the `Package.swift`? If not, I'd consider making this logic reusable to prevent inconsistencies.

File: Sources/TuistKit/Mappers/Graph/StaticXCFrameworkModuleMapGraphMapper.swift [hunk 5]
```diff
@@ -0,0 +1,182 @@
...
+                            return nil
+                        }
+                    }
+
+                guard !staticObjcXCFrameworksLinkedByDynamicXCFrameworkDependencies.isEmpty else { continue }
+
+                sideEffects += try self.sideEffects(
+                    for: staticObjcXCFrameworksLinkedByDynamicXCFrameworkDependencies,
+                    derivedDirectory: derivedDirectory
+                )
```
Comment (pepicrft) [inline Sources/TuistKit/Mappers/Graph/StaticXCFrameworkModuleMapGraphMapper.swift:45]: The lack of semantics in `self.SideEffects` makes it a bit hard what those side effects are all about. What about?

```suggestion
                sideEffects += try self.removeModuleFromHeaderImports(
                    for: staticObjcXCFrameworksLinkedByDynamicXCFrameworkDependencies,
                    derivedDirectory: derivedDirectory
                )
```

Feel free to adjust to anything that feels more accurate to you.

File: Sources/TuistKit/Mappers/Graph/StaticXCFrameworkModuleMapGraphMapper.swift [hunk 6]
```diff
@@ -0,0 +1,182 @@
...
+                else { return [] }
+                let name = xcframework.path.basenameWithoutExt
+                let umbrellaHeader = moduleMap.parentDirectory.appending(component: "\(name).h")
+                guard fileHandler.exists(umbrellaHeader)
+                else { return [] }
+                return [
+                    .directory(DirectoryDescriptor(path: derivedDirectory.appending(components: name, "Headers"))),
+                    .file(
+                        FileDescriptor(
+                            path: derivedDirectory.appending(components: name, "Headers", "module.modulemap"),
```
Comment (pepicrft) [inline Sources/TuistKit/Mappers/Graph/StaticXCFrameworkModuleMapGraphMapper.swift:133]: This file contains `derivedDirectory.appending(components: name, "Headers", ...)` in a few places. I'd pass that `headersDirectory` around, or have a function to obtain the headers directory from the derived one.

File: Sources/TuistKit/Mappers/Graph/StaticXCFrameworkModuleMapGraphMapper.swift [hunk 7]
```diff
@@ -0,0 +1,182 @@
...
+        )
+    }
+
+    private func moduleMapFlag(
+        for xcframework: GraphDependency.XCFramework,
+        derivedDirectory: AbsolutePath,
+        project: Project
+    ) -> String {
+        let name = xcframework.path.basenameWithoutExt
+        return "-fmodule-map-file=\"$(SRCROOT)/\(derivedDirectory.appending(components: name, "Headers", "module.modulemap").relative(to: project.path).pathString)\""
```
Comment (pepicrft) [inline Sources/TuistKit/Mappers/Graph/StaticXCFrameworkModuleMapGraphMapper.swift:97]: Am I missing something, or will this break if we have to do this for more than one dependency in the graph? Should we create sub-directories under `Headers` to scope `module.modulemap` for each XCFramework?

File: Sources/TuistKit/Mappers/Graph/StaticXCFrameworkModuleMapGraphMapper.swift [hunk 8]
```diff
@@ -0,0 +1,182 @@
...
+        fileHandler: FileHandling = FileHandler.shared
+    ) {
+        self.fileHandler = fileHandler
+    }
+
+    public func map(graph: Graph, environment: MapperEnvironment) throws -> (Graph, [SideEffectDescriptor], MapperEnvironment) {
+        let derivedDirectory = derivedDirectory(graph: graph)
+
+        var sideEffects: [SideEffectDescriptor] = []
+        var settingsToPropagate: [GraphDependency: SettingsDictionary] = [:]
```
Comment (pepicrft) [inline Sources/TuistKit/Mappers/Graph/StaticXCFrameworkModuleMapGraphMapper.swift:20]: Why not mapping `projects` and `targets` directly instead of persisting the settings to propagate and mutating them in another traverse?

File: Sources/TuistKit/Mappers/Graph/StaticXCFrameworkModuleMapGraphMapper.swift (hunk 2 above)
Comment (fortmarek) [reply Sources/TuistKit/Mappers/Graph/StaticXCFrameworkModuleMapGraphMapper.swift:8]: It'd mean rewriting the `GraphMapping` module which is out of scope here

File: Sources/TuistKit/Mappers/Graph/StaticXCFrameworkModuleMapGraphMapper.swift (hunk 7 above)
Comment (fortmarek) [reply Sources/TuistKit/Mappers/Graph/StaticXCFrameworkModuleMapGraphMapper.swift:97]: This is already scoped per xcframework

File: Sources/TuistCore/Graph/GraphTraverser.swift (hunk 1 above)
Comment (fortmarek) [reply Sources/TuistCore/Graph/GraphTraverser.swift:473]: I'm not sure I agree. Why load this information _always_ in memory if we need it in a single place? And increasing the API surface of `XcodeGraph` for something I'd consider very niche?

File: Sources/TuistKit/Mappers/Graph/StaticXCFrameworkModuleMapGraphMapper.swift (hunk 8 above)
Comment (fortmarek) [reply Sources/TuistKit/Mappers/Graph/StaticXCFrameworkModuleMapGraphMapper.swift]: I removed one extra pass. We still need to do two of them as we need to go through the targets topologically sorted. One extra pass shouldn't be expensive, though, so I think it's fine, although there are probably ways how to update the settings in place if the settings is computed on demand in a DFS-fashion.

**Review by pepicrft — COMMENTED** [review]
I left some minor comments.

File: Sources/TuistCore/Graph/GraphTraverser.swift (hunk 1 above)
Comment (pepicrft) [reply Sources/TuistCore/Graph/GraphTraverser.swift:473]: > I'm not sure I agree. Why load this information always in memory if we need it in a single place?

A quick search of `**/*.swiftmodule` and `**/*.modulemap` reveals two instances of the logic in the PR. 

Most of the metadata we load for XCFrameworks could be considered a niche since we'll be the main consumers of `XcodeGraph`, even after we extract the generation logic. My concern is that if we don't draw a line, we'll have a scattering of properties across the two repositories, so future contributions will find themselves having to decide where something should go.

Comment (fortmarek) [reply Sources/TuistCore/Graph/GraphTraverser.swift:473]: > My concern is that if we don't draw a line, we'll have a scattering of properties across the two repositories, so future contributions will find themselves having to decide where something should go.

Agree, but that doesn't mean shoving everything into `XcodeGraph`. We should limit the amount of PRs we need to do for `XcodeGraph` as doing cross-repo PRs is painful. This super tight coupling is not great and we should aim for `XcodeGraph` to be more generic and thus stable. If we're to put every little change into `XcodeGraph` for a niche use case of `tuist`, it's gonna be very hard to keep `XcodeGraph` stable.

Comment (pepicrft) [reply Sources/TuistCore/Graph/GraphTraverser.swift:473]: > We should limit the amount of PRs we need to do for XcodeGraph as doing cross-repo PRs is painful

This is a bad sign to me. If we refrain from adding changes to the model because of the pain of our architecture, we should either make that less painful or eliminate the pain. 

When I look at the [metadata](https://github.com/tuist/XcodeGraph/blob/12462c8fff97fc5efb8476ef4625f434acd5058f/Sources/XcodeGraph/Models/Metadata/XCFrameworkMetadata.swift#L6), it's not obvious to me which ones of those properties should be there because they are not used in a "niche" use case, and which ones should not because they are. 

Since the direction of XcodeGraph and the idea of extracting the generation logic is not clear, let's discuss that separately, merge this PR, and iterate on this if needed based on the conclusion of that discussion.

**Review by pepicrft — APPROVED** [review]
