### ISSUE TITLE
Unable to run latest tuist release 2.2.1 on Xcode 13.0/Swift 5.5

### ISSUE THREAD

**Issue by juyan** [tuist/tuist#3676]
**Describe the bug**
Pin tuist version to 2.2.1 by adding `.tuist-version` and set content to 2.2.1, then run `tuist generate` and got following error

```
The 'swift' command exited with error code 1 and message:
Project.swift:1:8: error: missing required module '_Concurrency'
import ProjectDescription
```

**To Reproduce**

1.  Have Xcode 13.0 installed(Swift 5.5)
2. Run `tuist generate` on any manifest file

**Expected behavior**
tuist command should work well on Xcode 13.0/Swift 5.5. Not everyone has upgraded to Xcode 13.1 yet.

**Screenshots**

**Desktop (please complete the following information):**

- OS: macOS
- Version 11.6

**Additional context**

**Comment by danyf90** [comment]
Hi Juyan, actually it's a problem with the Concurrency framework not available on macOS < 12 (Monterey).
It was not intended and we'll soon release a new build fixing this 🚀

**Comment by dp221125** [comment]
So, I installed xCode13.1 and it solved.
