### ISSUE TITLE
Tuist Adds Multiple .DS_Store files in Copy Bundle Resources phase

### ISSUE THREAD

**Issue by pavel-trafimuk** [tuist/tuist#6991]
### What happened?

After upgrading from 4.31.0 to 4.32.1 we have issues with compilation:
multiple .DS_Store files from several Resources folders added to the final target via Copy Bundle Resources phase.

As Xcode compilation doesn't support same filenames for iOS (think, macOS too) - in results we have fail

<img width="1001" alt="Zrzut ekranu 2024-11-4 o 22 40 43" src="https://github.com/user-attachments/assets/e63366f2-c6da-4143-918b-5e0f5be9f106">

Can't reproduce on 4.31.0

I found that it could be a result of https://github.com/tuist/tuist/pull/6970
I understand that this is main idea - include hidden files, but I think .DS_Store should be excluded otherwise app file have compilation error.

### How do we reproduce it?

To reproduce you should have several folder in resources with .DS_Store files inside (try to move icons in Finder or change grouping/sorting to generate this file) 

### Error log

```
Multiple commands produce 
'.../Library/Developer/Xcode/DerivedData/App-HASH/Build/Products/Debug-iphonesimulator/
App.app/.DS_Store'
• Target 'AppTarget' (project 'App') has copy command from '/X/App/DevelopmentResources/.DS_Store' to '/X/Library/ Developer/code/DerivedData/App-HASS/Build/Products/Deb...
Target 'AppTarget' (project 'App') has copy command from '/X/App/Resources/.DS_Store' to '/X/Library/Developer/ Xcode/DerivedData/App-HASH/Build/Products/Debug-iphone...
```

(error redacted)

### macOS version

15.1

### Tuist version

4.32.1

### Xcode version

16.0
