### ISSUE TITLE
Reconsider generic force-loading of static binary-target wrappers

### ISSUE THREAD

**Issue by Loupehope** [tuist/tuist#12183]
### Why is this needed?

This follows #10947 and its implementation in #10953. While #10947 correctly identified empty wrappers, it may be useful to reconsider the generic `-force_load` behavior added in #10953.

An empty SwiftPM wrapper target is a normal package layout mechanism. It exposes a product in the dependency graph and connects a binary target with its transitive dependencies. It does not imply that a dynamic wrapper must absorb or re export every object in the underlying static archive.

Before #10953, static binaries used normal archive selection semantics. Since the empty wrapper referenced no archive symbols, no members were selected and the wrapper remained empty. That is expected behavior for a static archive. Declaring the SwiftPM product as `.framework` alone does not request that all members be included in a dynamic library.

Force loading can help simple Swift or Objective C libraries, but it is not safe as a generic rule for vendor static XCFrameworks. Such archives may contain private ObjC metadata, duplicate members, or unused objects with unresolved dependencies. These details are harmless under ordinary archive selection but can fail when every member is loaded.

### Reproduction

Repo: https://github.com/Loupehope/tuist-force-load-repro
Pinned version: Tuist 4.204.0-rc.1
Run: `mise install; ./verify.sh`

The repro contains three static XCFramework cases, each exposed through an intentionally empty wrapper target:

1. PrivateObjC: force loading places private ObjC metadata in the wrapper. Importing the binary module autolinks another copy, leaving the same class metadata in two dynamic images.
2. CxxDuplicates: the archive contains the same dependency object twice. Normal selection avoids the duplicate. Force loading loads both and produces a duplicate C++ symbol error.
3. CxxUndefined: an unused debug only object has an unresolved `debug::Probe::Initialize()` reference. Normal selection ignores it. Force loading selects it and the link fails.

### Results

With static products, all three consumers build successfully.

With dynamic products on Tuist 4.204.0-rc.1, Tuist emits `-Wl,-force_load` for the static XCFrameworks. The ObjC case only builds because another copy is autolinked. The C++ cases fail with duplicate and undefined symbol errors.

Converting these fixtures explicitly to dynamic XCFrameworks makes all consumers build. The conversion handles required ObjC metadata, duplicate native members, and the debug only object without manual force load or re export flags.

### Requested change:

Consider removing or disabling by default the automatic `-Wl,-force_load` injection introduced by #10953 for direct static XCFramework dependencies of dynamic targets. If retained, an explicit opt in path may be preferable.

Related PR: https://github.com/tuist/tuist/pull/12202

**Comment by Loupehope** [comment]
Dynamic promotion is risky beyond empty wrapper targets. For example, consider this initially static SwiftPM dependency graph:

<img width="574" height="176" alt="Image graph" src="https://github.com/user-attachments/assets/5987b7e5-a1bf-459d-a59b-7b64797046d9" />

In this graph, both A and B reach the same static archive. With static linking, that archive is handled at the final link boundary using normal archive-member selection: only members needed to resolve symbols are selected.

If the product and its lower targets are instead turned into dynamic frameworks, the shared static XCFramework may be absorbed independently through both A and B. This can cause duplicated native symbols, global state, or Objective-C runtime metadata.

**Comment by Loupehope** [comment]
@shgew @pepicrft let's discuss this :)

**Comment by Loupehope** [comment]
I’d also like to mention that the changes in https://github.com/tuist/tuist/pull/10953 broke XCFramework integration in my projects because of the forced `-force_load`.

From my perspective, it would be better to avoid adding behavior to Tuist that does not work universally, as the examples above show, especially when the problem can already be handled locally with the existing tools.

For example, in https://github.com/shgew/tuist-spm-wrapper-deadstrip, the GoogleMobileAds issue discussed in https://github.com/tuist/tuist/issues/10947 can be addressed through `PackageSettings`:

```swift
// Solution using -ObjC and PackageSettings
let packageSettings = PackageSettings(
    productTypes: ["GoogleMobileAds": .framework],
    targetSettings: [
        "GoogleMobileAdsTarget": [
            "OTHER_LDFLAGS": "$(inherited) -ObjC -framework JavaScriptCore"
        ]
    ]
)

// ------------------

// Solution using -force_load and PackageSettings
let packageSettings = PackageSettings(
    productTypes: ["GoogleMobileAds": .framework],
    targetSettings: [
        "GoogleMobileAdsTarget": [
            "OTHER_LDFLAGS": .string(
                "$(inherited) -Wl,-force_load,$(BUILT_PRODUCTS_DIR)/GoogleMobileAds.framework/GoogleMobileAds -framework JavaScriptCore"
            )
        ]
    ]
)
```

Also, converting static libraries into dynamic libraries is a fairly complex task and usually requires handling many related details. This is not meant as an advertisement, but I understand this from working on https://github.com/Loupehope/DylibForge, a tool for converting static archives without source code into dynamic libraries while avoiding side effects.

**Comment by shgew** [comment]
I won't pretend to understand linking at the level you guys do, so I don't think I am ready to offer my take on what the solution should be. I am here, however, to provide more context on the issue I have created originally if you need it. 

From my side, I would definitely not default to something that breaks projects. And in general what @Loupehope says sounds very compelling.
