### ISSUE TITLE
Dependencies.swift not being able to use Firebase 9.0.0

### ISSUE THREAD

**Issue by unxavi** [tuist/tuist#4444]
## Describe the bug and the expected behavior

Firebase 9.0.0 is not able to compile in a project generated by Tuist 3.3.0.

When running the command `tuist cache warm`

We are getting a bunch of 

```
FIRApp.h:47:1: error: duplicate interface definition for class 'FIRApp'
@interface FIRApp : NSObject
^
In module 'FirebaseCore' imported from /userPath/app_with_spm_dependencies/Tuist/Dependencies/SwiftPackageManager/.build/checkouts/firebase-ios-sdk/FirebaseCore/Extension/FirebaseCoreInternal.h:15:
/userPath/Library/Developer/Xcode/DerivedData/Tuistplayground-ewnvxgjotcrynkgqopiztlsrhvww/Build/Products/Debug-iphonesimulator/FirebaseCore.framework/Headers/FIRApp.h:47:12: note: previous definition is here
@interface FIRApp : NSObject 

```

## Reproduction steps

Steps to reproduce the bug:

1. Use the attached sample project [app_with_spm_dependencies.zip](https://github.com/tuist/tuist/files/8680924/app_with_spm_dependencies.zip)
2. Run `tuist fetch`
3. Run `tuist cache warm --xcframeworks`

The same would happen if not using cache

1. Run `tuist fetch`
2. Run `tuist generate`
3. Compile the project on XCode

### Error log

```
FIRApp.h:47:1: error: duplicate interface definition for class 'FIRApp'
@interface FIRApp : NSObject
^
In module 'FirebaseCore' imported from /userPath/app_with_spm_dependencies/Tuist/Dependencies/SwiftPackageManager/.build/checkouts/firebase-ios-sdk/FirebaseCore/Extension/FirebaseCoreInternal.h:15:
/userPath/Library/Developer/Xcode/DerivedData/Tuistplayground-ewnvxgjotcrynkgqopiztlsrhvww/Build/Products/Debug-iphonesimulator/FirebaseCore.framework/Headers/FIRApp.h:47:12: note: previous definition is here
@interface FIRApp : NSObject 
```

### Error screenshots

<img width="681" alt="image" src="https://user-images.githubusercontent.com/3817679/168121716-f99e112d-4563-4ff6-a3f2-edb0c1f4b1dd.png">

### Additional context

- macOS version: 12.2.1
- Tuist version: 3.3.0
- Xcode version: 13.3.1

**Comment by fortmarek** [comment]
Hey @unxavi 👋 

First of all, thanks for including the reproducible project!

The reason boils down to this error message:
> /Users/marekfort/Downloads/app_with_spm_dependencies/Tuist/Dependencies/SwiftPackageManager/.build/checkouts/firebase-ios-sdk/FirebaseCore/Sources/Public/FirebaseCore/FIRApp.h:47:1: error: duplicate interface definition for class 'FIRApp'
@interface FIRApp : NSObject
^
In module 'FirebaseCore' imported from /Users/marekfort/Downloads/app_with_spm_dependencies/Tuist/Dependencies/SwiftPackageManager/.build/checkouts/firebase-ios-sdk/FirebaseCore/Extension/FirebaseCoreInternal.h:15:
/Users/marekfort/Library/Developer/Xcode/DerivedData/Tuistplayground-cvhvboxfvqlfdmdcxxltnxgkyakz/Build/Products/Debug-iphonesimulator/FirebaseCore.framework/Headers/FIRApp.h:47:12: note: previous definition is here
@interface FIRApp : NSObject

As the error message suggest, we include `FIRApp.h` header _twice_ - once as a part of the `......../DerivedData/......./FirebaseCore.framework/Headers` and then in the `FirebaseCore/Sources/Public/FirebaseCore`.

![image](https://user-images.githubusercontent.com/9371695/168225966-9d099dca-0671-4c06-9535-6fa637c52651.png)

In the screenshot, you can see the build settings of `FirebaseInstallations`. If you remove the last entry (public headers of `FirebaseCore`), the target's build will succeed. Since public headers are bundled with the framework and the framework is a dependency of `FirebaseInstallations` (so it will always be built before it), I think we should _not_ add the path to them to the header search paths. They are added [here](https://github.com/tuist/tuist/blob/main/Sources/TuistDependencies/SwiftPackageManager/Utils/PackageInfoMapper.swift#L739-L746). But I presume in some cases they are necessary.

It would also be worth looking into how `Firebase` was set up before and what changed that it's now broken. cc @danyf90

**Comment by mflknr** [comment]
Just a +1, I am experiencing the same right now.

**Comment by mfcollins3** [comment]
I was able to work around the issue for now by reverting to the old way of adding the package dependency to my Project object in Project.swift. It works until this issue gets figured out.

**Comment by danyf90** [comment]
Created a draft PR to play with and eventually fix it here: https://github.com/tuist/tuist/pull/4456

@fortmarek I would suggest to use `--no-cache` when running tuist generate to investigate this.

AFAIR the header search path should be used only if the dependency is not using public headers, not sure why we are adding it here 🤔

**Comment by malcommac** [comment]
I'm experiencing a similar issue with 9.2; `Undefined symbol: _OBJC_CLASS_$_FIRApp` is the error.  
I'm declaring dependencies using the old way inside the Project.swift file.

```
Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_FIRApp", referenced from:
      objc-class-ref in RealFlagsFirebase.o
ld: symbol(s) not found for architecture arm64
```

Is this a know issue or should I provide an example project?  
I've not figured a workaround to the problem yet.

**Comment by malcommac** [comment]
Hi @danyf90, I'll open a separate issue to avoid noise here. Thanks 👍
