### ISSUE TITLE
ObjC dynamic framework SPM dependencies missing Tuist-derived bundle accessor files since 4.146.0

### ISSUE THREAD

**Issue by Fab1n** [tuist/tuist#9645]
### What happened?

After upgrading from Tuist 4.145.0 to 4.146.0, ObjC SPM dependencies configured as dynamic frameworks (`.framework`) fail to compile because the `tuist-derived` bundle accessor files (`TuistBundle+<Target>.h` and `TuistBundle+<Target>.m`) are not wired into the generated Xcode project:

- The `.h` file is not set in `GCC_PREFIX_HEADER`
- The `.m` file is not added to the compile sources build phase
- The `tuist-derived` folder does not appear in the Xcode project navigator

The files are generated on disk but simply not referenced by the project.

This was introduced by PR #9446 (revert static framework resource embedding). The condition in `ResourcesProjectMapper.mapTarget` changed:

```swift
// Before (4.145.0):
let shouldGenerateResourceBundle = !supportsResources && target.product != .staticFramework

// After (4.146.0):
if !target.supportsResources || target.product == .staticFramework {
```

For dynamic frameworks, `supportsResources` is `true` and `product != .staticFramework`, so `false || false` evaluates to `false` — the entire resource mapping block is skipped, including the logic that wires synthesized `TuistBundle+` files into the Xcode project.

### How do we reproduce it?

1. Add an ObjC SPM dependency that has resources (e.g., [AffirmSDK](https://github.com/Affirm/affirm-merchant-sdk-ios))
2. Configure it as a dynamic framework in `Package.swift`:
```swift
let packageSettings = PackageSettings(
  productTypes: [
    "AffirmSDK": .framework,
  ]
)
```
3. Run `tuist generate`
4. Build — compilation fails with `Use of undeclared identifier 'SWIFTPM_MODULE_BUNDLE'`

### Error log

```
/path/to/Tuist/.build/checkouts/affirm-merchant-sdk-ios/SPM/AffirmUtils.m:62:12
Use of undeclared identifier 'SWIFTPM_MODULE_BUNDLE'
```

### macOS version

26.3

### Tuist version

4.146.0 (first regression version after 4.145.0)

### Xcode version

26.3
