### PR TITLE
Support for M1

### PR DESCRIPTION
**Pull request by pepibumur**
Resolves https://github.com/tuist/tuist/issues/2082

### Short description 📝
I'm updating the release scripts to ensure that all the binaries and frameworks that we provide have support for x86 and arm64.

### CODE REVIEW

**Review by RomainBoulay — APPROVED** [review]

File: Sources/TuistSupport/Utils/Environment.swift [hunk 1]
```diff
@@ -34,6 +34,9 @@ public protocol Environmenting: AnyObject {
 
     /// Returns the path to the directory where the async queue events are persisted.
     var queueDirectory: AbsolutePath { get }
+    
+    /// Returns true if the environment is ARM.
+    var isArm: Bool { get }
```
Comment (fortmarek) [inline Sources/TuistSupport/Utils/Environment.swift:39]: where will be this new property used? Or is this just laying some groundwork to get the M1 support going?

Comment (RomainBoulay) [inline Sources/TuistSupport/Utils/Environment.swift:39]: What about using an "Architecture" enum here instead of a boolean? I guess we shouldn't expect more processor architectures, but at least in term of readability I think that the enum reads better than a bool.

Comment (pepibumur) [reply Sources/TuistSupport/Utils/Environment.swift:39]: I don't think we'll need to use it in the end. The only thing we'll have to do is extending our release logic to build the binaries and the libraries to include both architectures, x86 and arm64. I'd still leave the method here in case we need it in the future.

**Comment by pepibumur** [comment]
When compiling using the Swift Package Manager and passing the following arguments `--arch arm64 --arch x86_64` the compilation fails:

```
/Users/pedropinera/src/github.com/tuist/tuist/.build/checkouts/swift-tools-support-core/Sources/TSCclibc/include/module.modulemap:1:8: note: previously defined here
module TSCclibc {
       ^
<module-includes>:3:9: error: could not build module 'CSQLite3'
#import "/Users/pedropinera/src/github.com/tuist/tuist/.build/checkouts/swift-tools-support-core/Sources/TSCclibc/include/csqlite3.h"
        ^
/Users/pedropinera/src/github.com/tuist/tuist/.build/checkouts/swift-tools-support-core/Sources/TSCBasic/Process.swift:17:29: error: could not build Objective-C module 'TSCclibc'
@_implementationOnly import TSCclibc
```

However, when architectures are compiled independently, the compilation succeeds. I'm thinking I can merge the architectures myself doing `lipo`, but I much prefer Swift Package Manager to do that for me.

**Comment by pepibumur** [comment]
A quick update on my previous comment. It turns out some packages we depend on fail to compile when we specify the 2 architectures and let Swift Package Manager compile the fat binaries for us. It only works when compiling the `ProjectDescription` framework. What I ended up doing for the `tuist` and `tuistenv` binaries is building the architectures independently, and them combining them using lipo.

**Review by RomainBoulay — APPROVED** [review]

**Review by fortmarek — APPROVED** [review]
