### ISSUE TITLE
Error: Ambiguous use of 'debug(name:settings:xcconfig:)'

### ISSUE THREAD

**Issue by muellerando** [tuist/tuist#540]
**Describe the bug**
Having 
 ` CustomConfiguration.debug(name: "Debug", settings: [:], xcconfig: "*.xcconfig")`
inside Project.swift File will break the build with Version 0.18.1

Error Message: 
```
tuist generate
Error: Command exited with error code 1 and error: /Project.swift:64:21: error: ambiguous use of 'debug(name:settings:xcconfig:)'
                    CustomConfiguration.debug(name: "Debug", settings: [:], xcconfig: "../Configuration/framework.test.xcconfig"),
                    ^
ProjectDescription.CustomConfiguration:2:24: note: found this candidate
    public static func debug(name: String, settings: [String : ProjectDescription.SettingValue] = [:], xcconfig: String? = nil) -> ProjectDescription.CustomConfiguration
                       ^
ProjectDescription.CustomConfiguration:4:24: note: found this candidate
    public static func debug(name: String, settings: [String : String], xcconfig: String? = nil) -> ProjectDescription.CustomConfiguration 
```
**Expected behavior**
Building the xcworkspace file

- Version 0.18.1

**Comment by kwridan** [comment]
Hi @muellerando 

There are two convenience methods to create custom configurations, one that takes in [`[String: String]`](https://github.com/tuist/tuist/blob/master/Sources/ProjectDescription/Settings.swift#L108) (deprecated but left in for backwards compatibility) and the other is [`[String: SettingValue]`](https://github.com/tuist/tuist/blob/master/Sources/ProjectDescription/Settings.swift#L102) (newer API). and sadly when using `[:]` the compiler is unable to determine which of those methods to use.

Seeing you don't have any settings, you can omit `settings` and the compiler should work out which method to use.

```
CustomConfiguration.debug(name: "Debug", xcconfig: "Debug.xcconfig")
```

For configuration files the relative path to the xcconfig file is needed, glob patterns aren't supported for this one.

Hope this helps!

**Comment by kwridan** [comment]
Alternatively if you don't need to use a custom configuration (one that isn't "Debug" or "Release" - e.g. "Beta"), there's another API you can use which uses the default "Debug" and "Release" configurations, while allowing you to specify an xcconfig file too.

https://docs.tuist.io/usage-project-swift#settings

```swift
Settings(debug: Configuration(xcconfig: "debug.xcconfig"), 
         release: Configuration(xcconfig: "release.xcconfig"))
```

**Comment by muellerando** [comment]
> Hi @muellerando
> 
> There are two convenience methods to create custom configurations, one that takes in [`[String: String]`](https://github.com/tuist/tuist/blob/master/Sources/ProjectDescription/Settings.swift#L108) (deprecated but left in for backwards compatibility) and the other is [`[String: SettingValue]`](https://github.com/tuist/tuist/blob/master/Sources/ProjectDescription/Settings.swift#L102) (newer API). and sadly when using `[:]` the compiler is unable to determine which of those methods to use.
> 
> Seeing you don't have any settings, you can omit `settings` and the compiler should work out which method to use.
> 
> ```swift
> CustomConfiguration.debug(name: "Debug", xcconfig: "Debug.xcconfig")
> ```
> 
> For configuration files the relative path to the xcconfig file is needed, glob patterns aren't supported for this one.
> 
> Hope this helps!

That really helps out. Could be pointed out in the docu that these parameters could be left away. (I hope I didn't over read it ;-) )
