### ISSUE TITLE
Unable to find module dependency

### ISSUE THREAD

**Issue by kapitoshka438** [tuist/tuist#9676]
### What happened?

When trying to migrate one of our super-large modular app from Xcodegen to Tuist framework-based project, we faced an issue when it cannot find Firebase and SVGKit module dependencies. Everything works fine with native SPM (both Xcodegen and Tuist).
I removed almost everything from our project to create a minimal reproducible sample and here it is: 
[tuistexample.zip](https://github.com/user-attachments/files/25698442/tuistexample.zip)

<img width="438" height="163" alt="Image" src="https://github.com/user-attachments/assets/9bcc71b8-2d68-41ba-bdb0-c44caf9495c4" />

### How do we reproduce it?

1. Use the attached sample project
2. `tuist install`
3. `tuist generate --cache-profile none`
4. Try to build the app

### Error log

```sh
error: Unable to find module dependency: 'FirebaseCrashlytics' (in target 'tuistexample' from project 'tuistexample')
note: A dependency of Swift module 'FirebaseFeatureModuleImp': '/Users/eminiakhmetov/Library/Developer/Xcode/DerivedData/tuistexample-edvobsoyossysnfgnermloaxztnn/Build/Products/Debug-iphonesimulator/FirebaseFeatureModuleImp.framework/Modules/FirebaseFeatureModuleImp.swiftmodule/arm64-apple-ios-simulator.swiftmodule' (in target 'tuistexample' from project 'tuistexample')
note: A dependency of main module 'tuistexample' (in target 'tuistexample' from project 'tuistexample')
error: Unable to find module dependency: 'FirebasePerformance' (in target 'tuistexample' from project 'tuistexample')
note: A dependency of Swift module 'FirebaseFeatureModuleImp': '/Users/eminiakhmetov/Library/Developer/Xcode/DerivedData/tuistexample-edvobsoyossysnfgnermloaxztnn/Build/Products/Debug-iphonesimulator/FirebaseFeatureModuleImp.framework/Modules/FirebaseFeatureModuleImp.swiftmodule/arm64-apple-ios-simulator.swiftmodule' (in target 'tuistexample' from project 'tuistexample')
note: A dependency of main module 'tuistexample' (in target 'tuistexample' from project 'tuistexample')
error: Unable to find module dependency: 'FirebaseCore' (in target 'tuistexample' from project 'tuistexample')
note: A dependency of Swift module 'FirebaseRemoteConfig': '/Users/eminiakhmetov/Library/Developer/Xcode/DerivedData/tuistexample-edvobsoyossysnfgnermloaxztnn/Build/Products/Debug-iphonesimulator/FirebaseRemoteConfig.framework/Modules/FirebaseRemoteConfig.swiftmodule/arm64-apple-ios-simulator.swiftmodule' (in target 'tuistexample' from project 'tuistexample')
note: A dependency of Swift module 'FirebaseFeatureModuleImp': '/Users/eminiakhmetov/Library/Developer/Xcode/DerivedData/tuistexample-edvobsoyossysnfgnermloaxztnn/Build/Products/Debug-iphonesimulator/FirebaseFeatureModuleImp.framework/Modules/FirebaseFeatureModuleImp.swiftmodule/arm64-apple-ios-simulator.swiftmodule' (in target 'tuistexample' from project 'tuistexample')
note: A dependency of main module 'tuistexample' (in target 'tuistexample' from project 'tuistexample')
error: Unable to find module dependency: 'FirebaseRemoteConfigInternal' (in target 'tuistexample' from project 'tuistexample')
note: A dependency of Swift module 'FirebaseRemoteConfig': '/Users/eminiakhmetov/Library/Developer/Xcode/DerivedData/tuistexample-edvobsoyossysnfgnermloaxztnn/Build/Products/Debug-iphonesimulator/FirebaseRemoteConfig.framework/Modules/FirebaseRemoteConfig.swiftmodule/arm64-apple-ios-simulator.swiftmodule' (in target 'tuistexample' from project 'tuistexample')
note: A dependency of Swift module 'FirebaseFeatureModuleImp': '/Users/eminiakhmetov/Library/Developer/Xcode/DerivedData/tuistexample-edvobsoyossysnfgnermloaxztnn/Build/Products/Debug-iphonesimulator/FirebaseFeatureModuleImp.framework/Modules/FirebaseFeatureModuleImp.swiftmodule/arm64-apple-ios-simulator.swiftmodule' (in target 'tuistexample' from project 'tuistexample')
note: A dependency of main module 'tuistexample' (in target 'tuistexample' from project 'tuistexample')
error: Unable to find module dependency: 'SVGKit' (in target 'tuistexample' from project 'tuistexample')
note: A dependency of Swift module 'CommonUI': '/Users/eminiakhmetov/Library/Developer/Xcode/DerivedData/tuistexample-edvobsoyossysnfgnermloaxztnn/Build/Products/Debug-iphonesimulator/CommonUI.framework/Modules/CommonUI.swiftmodule/arm64-apple-ios-simulator.swiftmodule' (in target 'tuistexample' from project 'tuistexample')
note: A dependency of Swift module 'UXFeedbackApi': '/Users/eminiakhmetov/Library/Developer/Xcode/DerivedData/tuistexample-edvobsoyossysnfgnermloaxztnn/Build/Products/Debug-iphonesimulator/UXFeedbackApi.framework/Modules/UXFeedbackApi.swiftmodule/arm64-apple-ios-simulator.swiftmodule' (in target 'tuistexample' from project 'tuistexample')
note: A dependency of Swift module 'AppsFlyerImp': '/Users/eminiakhmetov/Library/Developer/Xcode/DerivedData/tuistexample-edvobsoyossysnfgnermloaxztnn/Build/Products/Debug-iphonesimulator/AppsFlyerImp.framework/Modules/AppsFlyerImp.swiftmodule/arm64-apple-ios-simulator.swiftmodule' (in target 'tuistexample' from project 'tuistexample')
note: A dependency of main module 'tuistexample' (in target 'tuistexample' from project 'tuistexample')
note: A dependency of Swift module 'CommonUI': '/Users/eminiakhmetov/Library/Developer/Xcode/DerivedData/tuistexample-edvobsoyossysnfgnermloaxztnn/Build/Products/Debug-iphonesimulator/CommonUI.framework/Modules/CommonUI.swiftmodule/arm64-apple-ios-simulator.swiftmodule' (in target 'tuistexample' from project 'tuistexample')
note: A dependency of Swift module 'CommonArchitecture': '/Users/eminiakhmetov/Library/Developer/Xcode/DerivedData/tuistexample-edvobsoyossysnfgnermloaxztnn/Build/Products/Debug-iphonesimulator/CommonArchitecture.framework/Modules/CommonArchitecture.swiftmodule/arm64-apple-ios-simulator.swiftmodule' (in target 'tuistexample' from project 'tuistexample')
note: A dependency of Swift module 'AppsFlyerImp': '/Users/eminiakhmetov/Library/Developer/Xcode/DerivedData/tuistexample-edvobsoyossysnfgnermloaxztnn/Build/Products/Debug-iphonesimulator/AppsFlyerImp.framework/Modules/AppsFlyerImp.swiftmodule/arm64-apple-ios-simulator.swiftmodule' (in target 'tuistexample' from project 'tuistexample')
note: A dependency of main module 'tuistexample' (in target 'tuistexample' from project 'tuistexample')
error: Unable to find module dependency: 'SVGKit' (in target 'tuistexample' from project 'tuistexample')
note: A dependency of Swift module 'ViewStyler': '/Users/eminiakhmetov/Library/Developer/Xcode/DerivedData/tuistexample-edvobsoyossysnfgnermloaxztnn/Build/Products/Debug-iphonesimulator/ViewStyler.framework/Modules/ViewStyler.swiftmodule/arm64-apple-ios-simulator.swiftmodule' (in target 'tuistexample' from project 'tuistexample')
note: A dependency of Swift module 'CommonUI': '/Users/eminiakhmetov/Library/Developer/Xcode/DerivedData/tuistexample-edvobsoyossysnfgnermloaxztnn/Build/Products/Debug-iphonesimulator/CommonUI.framework/Modules/CommonUI.swiftmodule/arm64-apple-ios-simulator.swiftmodule' (in target 'tuistexample' from project 'tuistexample')
note: A dependency of Swift module 'CommonArchitecture': '/Users/eminiakhmetov/Library/Developer/Xcode/DerivedData/tuistexample-edvobsoyossysnfgnermloaxztnn/Build/Products/Debug-iphonesimulator/CommonArchitecture.framework/Modules/CommonArchitecture.swiftmodule/arm64-apple-ios-simulator.swiftmodule' (in target 'tuistexample' from project 'tuistexample')
note: A dependency of Swift module 'AppsFlyerImp': '/Users/eminiakhmetov/Library/Developer/Xcode/DerivedData/tuistexample-edvobsoyossysnfgnermloaxztnn/Build/Products/Debug-iphonesimulator/AppsFlyerImp.framework/Modules/AppsFlyerImp.swiftmodule/arm64-apple-ios-simulator.swiftmodule' (in target 'tuistexample' from project 'tuistexample')
note: A dependency of main module 'tuistexample' (in target 'tuistexample' from project 'tuistexample')
error: Unable to find module dependency: 'SVGKit' (in target 'tuistexample' from project 'tuistexample')
note: A dependency of Swift module 'ViewStylerHelper': '/Users/eminiakhmetov/Library/Developer/Xcode/DerivedData/tuistexample-edvobsoyossysnfgnermloaxztnn/Build/Products/Debug-iphonesimulator/ViewStylerHelper.framework/Modules/ViewStylerHelper.swiftmodule/arm64-apple-ios-simulator.swiftmodule' (in target 'tuistexample' from project 'tuistexample')
note: A dependency of Swift module 'ViewStyler': '/Users/eminiakhmetov/Library/Developer/Xcode/DerivedData/tuistexample-edvobsoyossysnfgnermloaxztnn/Build/Products/Debug-iphonesimulator/ViewStyler.framework/Modules/ViewStyler.swiftmodule/arm64-apple-ios-simulator.swiftmodule' (in target 'tuistexample' from project 'tuistexample')
note: A dependency of Swift module 'CommonUI': '/Users/eminiakhmetov/Library/Developer/Xcode/DerivedData/tuistexample-edvobsoyossysnfgnermloaxztnn/Build/Products/Debug-iphonesimulator/CommonUI.framework/Modules/CommonUI.swiftmodule/arm64-apple-ios-simulator.swiftmodule' (in target 'tuistexample' from project 'tuistexample')
note: A dependency of Swift module 'CommonArchitecture': '/Users/eminiakhmetov/Library/Developer/Xcode/DerivedData/tuistexample-edvobsoyossysnfgnermloaxztnn/Build/Products/Debug-iphonesimulator/CommonArchitecture.framework/Modules/CommonArchitecture.swiftmodule/arm64-apple-ios-simulator.swiftmodule' (in target 'tuistexample' from project 'tuistexample')
note: A dependency of Swift module 'AppsFlyerImp': '/Users/eminiakhmetov/Library/Developer/Xcode/DerivedData/tuistexample-edvobsoyossysnfgnermloaxztnn/Build/Products/Debug-iphonesimulator/AppsFlyerImp.framework/Modules/AppsFlyerImp.swiftmodule/arm64-apple-ios-simulator.swiftmodule' (in target 'tuistexample' from project 'tuistexample')
note: A dependency of main module 'tuistexample' (in target 'tuistexample' from project 'tuistexample')
```

### macOS version

26.3

### Tuist version

4.153.0

### Xcode version

26.2

**Comment by pepicrft** [comment]
@kapitoshka438 the fix will go out in the next release.

**Comment by kapitoshka438** [comment]
> [@kapitoshka438](https://github.com/kapitoshka438) the fix will go out in the next release.

Thank you @pepicrft 
I have tried 4.154.0 on the attached sample but the issue hasn't gone.

**Comment by Link184** [comment]
@pepicrft I see you unleashed the claude into this project, could that be the reason of quality regression?
btw the issue is not fixed with the latest 4.154.0 version

**Comment by pepicrft** [comment]
We've got the fix [here](https://github.com/tuist/tuist/pull/9692), @Link184, it'd be awesome if you could check it out locally and run it against your project. Answering to your point about a potential connection between coding agents and regressions. 

With more projects adopting generated projects and new scenarios popping up, reasoning about the graph has become trickier. This is undocumented knowledge that we try to validate through fixtures, but the number of scenarios out there is vast. That sadly means some fixes might introduce new regressions. We can't afford to have too many acceptance tests because it'd slow us down significantly (they already do), so finding a good balance here is tricky.

I know it sounds frustrating, and I apologize for that, but there are many scenarios that would have taken us years to address, so it's very positive that we have these tools today. The undocumented intricacies of Xcode are tricky to bear with.

**Comment by kapitoshka438** [comment]
@pepicrft with 4.154.5 version the "Unable to find module dependency" errors are gone, but now there's another error:
```
ld: warning: Could not find or use auto-linked framework 'UIUtilities': framework 'UIUtilities' not found
ld: warning: Could not parse or use implicit file '/Applications/Xcode-26.2.0.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/Frameworks/SwiftUICore.framework/SwiftUICore.tbd': cannot link directly with 'SwiftUICore' because product being built is not an allowed client of it
Undefined symbols for architecture arm64:
  "_main", referenced from:
      ___debug_main_executable_dylib_entry_point in command-line-aliases-file
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by pepicrft** [comment]
Where can I reproduce that issue?

**Comment by kapitoshka438** [comment]
> Where can I reproduce that issue?

There's a example project attached to this issue

**Comment by Link184** [comment]
@pepicrft Thank you for a quick answer and a very quick solution. Unfortunately the solution is not working with version 4.154.5

**Comment by pepicrft** [comment]
> [@pepicrft](https://github.com/pepicrft) with 4.154.5 version the "Unable to find module dependency" errors are gone, but now there's another error:
> 
> ```
> ld: warning: Could not find or use auto-linked framework 'UIUtilities': framework 'UIUtilities' not found
> ld: warning: Could not parse or use implicit file '/Applications/Xcode-26.2.0.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/Frameworks/SwiftUICore.framework/SwiftUICore.tbd': cannot link directly with 'SwiftUICore' because product being built is not an allowed client of it
> Undefined symbols for architecture arm64:
>   "_main", referenced from:
>       ___debug_main_executable_dylib_entry_point in command-line-aliases-file
> ld: symbol(s) not found for architecture arm64
> clang: error: linker command failed with exit code 1 (use -v to see invocation)
> ```

The `_main` error is caused by `Dummy` not having a `@main` or `UIApplicationMain`. An `.app` target requires a main symbol.

**Comment by pepicrft** [comment]
> [@pepicrft](https://github.com/pepicrft) Thank you for a quick answer and a very quick solution. Unfortunately the solution is not working with version 4.154.5

@Link184 any chance you can share a project where I can reproduce the issue that you are facing?

**Comment by kapitoshka438** [comment]
> > [@pepicrft](https://github.com/pepicrft) with 4.154.5 version the "Unable to find module dependency" errors are gone, but now there's another error:
> > 
> > ```
> > ld: warning: Could not find or use auto-linked framework 'UIUtilities': framework 'UIUtilities' not found
> > ld: warning: Could not parse or use implicit file '/Applications/Xcode-26.2.0.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/Frameworks/SwiftUICore.framework/SwiftUICore.tbd': cannot link directly with 'SwiftUICore' because product being built is not an allowed client of it
> > Undefined symbols for architecture arm64:
> >   "_main", referenced from:
> >       ___debug_main_executable_dylib_entry_point in command-line-aliases-file
> > ld: symbol(s) not found for architecture arm64
> > clang: error: linker command failed with exit code 1 (use -v to see invocation)
> > ```
> 
> The `_main` error is caused by `Dummy` not having a `@main` or `UIApplicationMain`. An `.app` target requires a main symbol.
> 
> 

Oh, my bad, I'm sorry 😅
Well it means the problem is gone. Thank you @pepicrft , you are my hero 🦸‍♂️
