### ISSUE TITLE
Tuist 4.8.0 installed with mise on x86, only compiled for arm64

### ISSUE THREAD

**Issue by mgray88** [tuist/tuist#6123]
### What happened?

Installing Tuist 4.8.0 with mise, it seems the ProjectDescription framework does not include swift interface files for x86. After updating to 4.8.0 and attempting to generate the project, the following error occurs:

```
[...]/Workspace.swift:1:8: error: could not find module 'ProjectDescription' for target 'x86_64-apple-macos'; found: arm64-apple-macos, at: /Users/[...]/.local/share/mise/installs/tuist/4.8.0/bin/ProjectDescription.framework/Modules/ProjectDescription.swiftmodule
import ProjectDescription
       ^
```

Mise: 2024.3.9

### How do we reproduce it?

Reproducible without any project at all, `tuist init` fails with similar error

### Error log

```
$ tuist init --verbose
tuist version
Dispatching persisted event with ID '8AF0DEEE-9DBE-48DF-BAC5-E68C8298E081' to 'TuistAnalytics'
4.8.0
/usr/bin/xcrun swift -version
Apple Swift version 5.10 (swiftlang-5.10.0.13 clang-1500.3.9.4)
Target: x86_64-apple-macosx14.0


/usr/bin/xcrun swift -suppress-warnings -I /Users/mike/.local/share/mise/installs/tuist/4.8.0/bin -L /Users/mike/.local/share/mise/installs/tuist/4.8.0/bin -F /Users/mike/.local/share/mise/installs/tuist/4.8.0/bin -lProjectDescription -framework ProjectDescription /Users/mike/.local/share/mise/installs/tuist/4.8.0/bin/Templates/default/default.swift --tuist-dump

The 'swift' command exited with error code 1 and message:
/Users/mike/.local/share/mise/installs/tuist/4.8.0/bin/Templates/default/default.swift:1:8: error: could not find module 'ProjectDescription' for target 'x86_64-apple-macos'; found: arm64-apple-macos, at: /Users/mike/.local/share/mise/installs/tuist/4.8.0/bin/ProjectDescription.framework/Modules/ProjectDescription.swiftmodule
import ProjectDescription
       ^
```

### macOS version

14.4

### Tuist version

4.8.0

### Xcode version

15.3.0

**Comment by fortmarek** [comment]
Hey 👋 

We'll look into this. In the meantime, could you share which version was the last one you could install on Intel? Knowing that might help us find the regression quicker.

**Comment by mgray88** [comment]
4.7.0 worked fine

**Comment by pepicrft** [comment]
@mgray88 it should be fixed now in [the latest version](https://github.com/tuist/tuist/releases/tag/4.8.1)
