### ISSUE TITLE
Issue with tuist fetch in 3.31.0 

### ISSUE THREAD

**Issue by icedice** [tuist/tuist#5564]
### What problem or need do you have?

After upgrading from 3.30.0 to 3.31.0 `tuist fetch` is no longer working. Did the update contain breaking changes?

```
Resolving and fetching plugins.
Plugins resolved and fetched successfully.
Updating dependencies.
The 'swift' command exited with error code 1 and message:
/Users/toke.refstrup/git/ios2/Tuist/Dependencies.swift:14:26: error: cannot convert value of type '[Any]' to expected argument type 'SwiftPackageManagerDependencies?'
    swiftPackageManager: [
                         ^
/Users/toke.refstrup/git/ios2/Tuist/Dependencies.swift:15:10: error: type 'Any' has no member 'remote'
        .remote(url: "https://github.com/layoutBox/PinLayout", requirement: .upToNextMajor(from: "1.10.3")),
        ~^~~~~~
```

### macOS version

14.1.1

### Tuist version

3.30.0

### Xcode version

15.0.1

**Comment by danyf90** [comment]
Probably it was breaking by mistake 🙏 
You can use `swiftPackageManager: .init([…` instead

**Comment by icedice** [comment]
> Probably it was breaking by mistake 🙏 You can use `swiftPackageManager: .init([…` instead

BTW will this be fixed in later release? I would do it my self but I was unable to follow the "contributor setup" I'm not sure if its outdated..
