### ISSUE TITLE
Unable to run tuist 2.5.0 on Big Sur

### ISSUE THREAD

**Issue by softmaxsg** [tuist/tuist#3938]
**Describe the bug**
Can not generate the project using `tuist generate` on Big Sur using Xcode 12.4 (12D4e), or Xcode 12.5 (12E262), or Xcode 13.0 (13A233). In all cases I receive the following output
```
Using version 2.5.0 defined at my-app/.tuist-version
Swift/ErrorType.swift:200: Fatal error: Error raised at top level: The 'swift' command exited with error code 1 and message:
/me/.tuist/Versions/2.5.0/ProjectDescription.framework/Modules/ProjectDescription.swiftmodule/x86_64-apple-macos.swiftinterface:6:8: error: no such module '_Concurrency'
import _Concurrency
       ^
my-app/Tuist/Config.swift:1:8: error: failed to build module 'ProjectDescription' from its module interface; the compiler that produced it, 'Apple Swift version 5.5.2 (swiftlang-1300.0.47.5 clang-1300.0.29.30)', may have used features that aren't supported by this compiler, 'Apple Swift version 5.3.2 (swiftlang-1200.0.45 clang-1200.0.32.28)'
import ProjectDescription
```

with the only difference in the part that mentions the version of my Swift Compiler

**To Reproduce**
- Use Big Sur with either Xcode 12.4 (12D4e), or Xcode 12.5 (12E262), or Xcode 13.0 (13A233)
- Run `tuist generate`

**Expected behavior**
tuist should work well on Big Sur with Xcode 12.4 or at least Xcode 12.5 and above

**Desktop (please complete the following information):**

- OS: macOS
- Version: 11.6.2 (20G314)

**Additional context**

There was [another issue](https://github.com/tuist/tuist/issues/3676), reporting the same problem and it [was fixed](https://github.com/tuist/tuist/pull/3731). However, somehow I am facing the same issue.

**Comment by adellibovi** [comment]
Thanks for reporting @softmaxsg , we are going to have a look. Big Sur should be supported.

**Comment by adellibovi** [comment]
@softmaxsg can you please check that when trying using Xcode 13 the Command Line Tools is correctly set this version?
You can use `xcode-select -p` to make sure it points to the correct version. Can you try again when doing so? Thanks!

**Comment by softmaxsg** [comment]
@adellibovi Thanks for your reply. Here is how it looks on my side

```
xcode-select -p                                
/Applications/Xcode_13.app/Contents/Developer

tuist generate                                 

Using version 2.5.0 defined at my-app/.tuist-version
Swift/ErrorType.swift:200: Fatal error: Error raised at top level: The 'swift' command exited with error code 1 and message:
me/.tuist/Versions/2.5.0/ProjectDescription.framework/Modules/ProjectDescription.swiftmodule/x86_64-apple-macos.swiftinterface:6:8: error: no such module '_Concurrency'
import _Concurrency
       ^
my-app/Tuist/Config.swift:1:8: error: failed to build module 'ProjectDescription'; this SDK is not supported by the compiler (the SDK is built with 'Apple Swift version 5.5.2 (swiftlang-1300.0.47.5 clang-1300.0.29.30)', while this compiler is 'Apple Swift version 5.5 (swiftlang-1300.0.31.1 clang-1300.0.29.1)'). Please select a toolchain which matches the SDK.
import ProjectDescription
       ^
```

**Comment by adellibovi** [comment]
Thanks @softmaxsg, we found the issue and we will try to fix it soon. In the meanwhile, as a workaround, you can use Xcode 13.2, which should work. 😄

**Comment by softmaxsg** [comment]
@adellibovi That was fast. Thanks!

**Comment by fortmarek** [comment]
We'll create a release during this week, so the support is added back as soon as possible.
