### ISSUE TITLE
RootDirectoryLocator refactor broke support for nested Workspaces

### ISSUE THREAD

**Issue by itsthejb** [tuist/tuist#5588]
### What happened?

Previously: https://github.com/tuist/tuist/issues/5586

I've bisected the issue to https://github.com/tuist/tuist/pull/5499.

While I understand the intent of the change, it breaks some of the power that was previously present. This may not be intended functionality, but it was previously possible and quite powerful, especially in mono-repo setups:

- Shared code through root `Tuist/ProjectDescriptionHelpers`
- Ability to nest `Workspace.swift`:
  - Repo root `Workspace.swift` covers every nested project
  - Nested project `Workspace.swift` allows focussed work on particular projects (common use case), _but also_ repo-wide shared behaviour through ProjectDescriptionHelpers

The refactoring breaks this since it now gives `Workspace.swift` precedence. This means that the root `ProjectDescriptionHelpers` aren't found and built. This explains the original issue reported in #5586

 

### How do we reproduce it?

- https://drive.google.com/file/d/1RNu46VaME_dSIYjX5hf66q8b3Ii9MXSO/view?usp=drive_link
- `tuist generate` (`3.30.0` is selected, this issue was introduced in this version)

### Error log

```
❯ tuist generate -n
Resolved cache profile 'Development' from Tuist's defaults
The 'swift' command exited with error code 1 and message:
../bug/Another/Project.swift:2:8: error: no such module 'ProjectDescriptionHelpers'
import ProjectDescriptionHelpers
       ^
```

- The nested `Another` module uses code shared from the root `ProjectDescriptionHelpers`
- Since `Another/Workspace.swift` exists, the root is not found and the helpers are not built. This is why it fails

### macOS version

14.1.1 (23B81)

### Tuist version

14.1.1 (23B81)

### Xcode version

15.0.1

**Comment by itsthejb** [comment]
I haven't dug very deeply into the code yet, but it seems that the approach relies only on the filesystem. Would it not solve and simplify the problem to use additional data points? For example Git itself can give the repo's root path directly from any place in a repo with `git -C <any path within a repo> rev-parse --show-toplevel`. With a filesystem only approach, this needs to be given the lowest precedence

**Comment by svenmuennich** [comment]
We're are facing the same problem. Our setup involves a mono-repo containing several apps and libraries, each having their own `Workspace.swift` and `Project.swift` files while the project descriptions helpers are shared and located in `<git root>/Tuist/ProjectDescriptionHelpers`.

Looking at the changes that broke this as well as the proposed fix (https://github.com/tuist/tuist/pull/5593) I wonder what the _root directory_ located using `RootDirectoryLocator`/`RootDirectoryLocating` is meant to represent. I would assume that _root directory_ to be the location of the workspace or project that is being generated or edited. So I'd consider the current behavior to be correct.

However, I would also assume the `Tuist` directory used e.g. for building the project description helpers to be allowed to be located _further up_ in the file system hierarchy. Just like e.g. SwiftLint and ESLint allow the used configuration file to be _further up_, even outside the git repository, if available.

Do you have any thoughts on this?

**Comment by itsthejb** [comment]
I suppose an alternative fix would be to require workspaces to have explicit links to a parent, except for when they're supposed to be independent. This would be arguably clearer.

So you could have:

```
.
├── Tuist
│   └── ProjectDescriptionHelpers
├── Workspace.swift (a)
├── Foo
│   └── Workspace.swift (b)
└── Bar
    └── Workspace.swift (c)
```

Workspaces:

- (a) Normal workspace
- (b) "Independent" workspace, defined same as (a). Doesn't/cannot link root `ProjectDescriptionHelpers`
- (c) "Child workspace. Adds additional argument to give parent link to (a). Could be defined something like:

```swift
import ProjectDescription
import ProjectDescriptionHelpers

let workspace = Workspace(
    name: "Child",
    projects: [...],
    parent: ".."
)
```

Would avoid any magic, I suppose

**Comment by pepicrft** [comment]
Sorry for the late response. https://github.com/tuist/tuist/pull/5499 should have never happened. Back when we designed the directory conventions, we agreed on using `Tuist/` as a reference to detect what's the root directory. We built logic on that assumption and ended up having users depending on that assumption too (you). We should stick to that convention instead.

**Comment by pepicrft** [comment]
Here's the [PR](https://github.com/tuist/tuist/pull/5637) addressing it.

**Comment by svenmuennich** [comment]
Thank you @pepicrft!

**Comment by itsthejb** [comment]
Makes sense to close this issue now then 👍
